// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/scottage.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_nullObject
Rcpp::List get_nullObject(Rcpp::XPtr<nullObject<float>> nm);
RcppExport SEXP _scottage_get_nullObject(SEXP nmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<nullObject<float>> >::type nm(nmSEXP);
    rcpp_result_gen = Rcpp::wrap(get_nullObject(nm));
    return rcpp_result_gen;
END_RCPP
}
// mk_nullObject_float
Rcpp::XPtr<nullObject<float>> mk_nullObject_float(Rcpp::List null_model);
RcppExport SEXP _scottage_mk_nullObject_float(SEXP null_modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type null_model(null_modelSEXP);
    rcpp_result_gen = Rcpp::wrap(mk_nullObject_float(null_model));
    return rcpp_result_gen;
END_RCPP
}
// mk_nullObject_double
Rcpp::XPtr<nullObject<double>> mk_nullObject_double(Rcpp::List null_model);
RcppExport SEXP _scottage_mk_nullObject_double(SEXP null_modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type null_model(null_modelSEXP);
    rcpp_result_gen = Rcpp::wrap(mk_nullObject_double(null_model));
    return rcpp_result_gen;
END_RCPP
}
// score_test_float
float score_test_float(Rcpp::XPtr<nullObject<float>> nm, Rcpp::NumericVector X);
RcppExport SEXP _scottage_score_test_float(SEXP nmSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<nullObject<float>> >::type nm(nmSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(score_test_float(nm, X));
    return rcpp_result_gen;
END_RCPP
}
// score_test_double
double score_test_double(Rcpp::XPtr<nullObject<double>> nm, Rcpp::NumericVector X);
RcppExport SEXP _scottage_score_test_double(SEXP nmSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<nullObject<double>> >::type nm(nmSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(score_test_double(nm, X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scottage_get_nullObject", (DL_FUNC) &_scottage_get_nullObject, 1},
    {"_scottage_mk_nullObject_float", (DL_FUNC) &_scottage_mk_nullObject_float, 1},
    {"_scottage_mk_nullObject_double", (DL_FUNC) &_scottage_mk_nullObject_double, 1},
    {"_scottage_score_test_float", (DL_FUNC) &_scottage_score_test_float, 2},
    {"_scottage_score_test_double", (DL_FUNC) &_scottage_score_test_double, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_scottage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
