# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_nullObject <- function(nm) {
    .Call(`_scottage_get_nullObject`, nm)
}

mk_nullObject_float <- function(null_model) {
    .Call(`_scottage_mk_nullObject_float`, null_model)
}

mk_nullObject_double <- function(null_model) {
    .Call(`_scottage_mk_nullObject_double`, null_model)
}

score_test_float <- function(nm, X) {
    .Call(`_scottage_score_test_float`, nm, X)
}

score_test_double <- function(nm, X) {
    .Call(`_scottage_score_test_double`, nm, X)
}

