# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_nullObject <- function(nm) {
    .Call(`_scottage_get_nullObject`, nm)
}

GWAS_score_test_AG_bed_float <- function(pA, p, times, beg, end, nm) {
    .Call(`_scottage_GWAS_score_test_AG_bed_float`, pA, p, times, beg, end, nm)
}

GWAS_score_test_AG_bed_double <- function(pA, p, times, beg, end, nm) {
    .Call(`_scottage_GWAS_score_test_AG_bed_double`, pA, p, times, beg, end, nm)
}

GWAS_score_test_AG_bed_float_TEST <- function(pA, p, times, beg, end, nm) {
    .Call(`_scottage_GWAS_score_test_AG_bed_float_TEST`, pA, p, times, beg, end, nm)
}

GWAS_score_test_AG_bed_double_TEST <- function(pA, p, times, beg, end, nm) {
    .Call(`_scottage_GWAS_score_test_AG_bed_double_TEST`, pA, p, times, beg, end, nm)
}

mk_nullObject_float <- function(null_model) {
    .Call(`_scottage_mk_nullObject_float`, null_model)
}

mk_nullObject_double <- function(null_model) {
    .Call(`_scottage_mk_nullObject_double`, null_model)
}

score_test_float <- function(nm, X) {
    .Call(`_scottage_score_test_float`, nm, X)
}

score_test_double <- function(nm, X) {
    .Call(`_scottage_score_test_double`, nm, X)
}

score_test_float_TEST <- function(nm, X) {
    .Call(`_scottage_score_test_float_TEST`, nm, X)
}

score_test_double_TEST <- function(nm, X) {
    .Call(`_scottage_score_test_double_TEST`, nm, X)
}

